name: uni_map_platform_interface
description: Uni Map Platform Interface.
version: 0.6.0-dev.2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  foundation_fluttify: ^0.12.0-dev.1
  core_location_fluttify: ^0.7.0-dev.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4